
import { Dictionary } from './types';

export const DICTIONARY: Dictionary = {
  FI: {
    title: "Tonttu Kuvaus",
    subtitle: "Löydä sisäinen tonttusi Lapin taian avulla",
    buttonBegin: "Aloita Taianomainen Matka",
    smileText: "Hymyile tonttu-kameralle",
    footerText: "Arctic AI Laboratory • Rovaniemi, Lappi ✨",
    capturing: "Tallennetaan sieluasi...",
    processing: "Tonttujen työpajassa...",
    processingSub: "Lapin tontut kutovat revontulien loistoa ja joulun taikaa muotokuvaasi",
    resultTitle: "Sinun Tonttu-portrettisi",
    backHome: "Uusi Taika",
    errorTitle: "Luminen este taikuuden tiellä.",
    errorAction: "Yritä Uudelleen",
    groupSelectTitle: "Kuka astuu taikaan?",
    groupSelectSingle: "Yksittäinen Tonttu",
    groupSelectSingleDesc: "Henkilökohtainen muodonmuutos",
    groupSelectGroup: "Perhe & Ystävät",
    groupSelectGroupDesc: "Koko ryhmän yhteinen tonttuhetki",
    selectStyleTitle: "Valitse Tonttutyylisi",
    styleClassic: "Perinteinen",
    styleFrost: "Pakkas-Tonttu",
    styleForest: "Metsä-Tonttu",
    styleRoyal: "Arvotonttu",
    btnStartMagic: "Luo Taikaa",
    btnUpscale: "Magian Terävöitys",
    upscaleLevelLabel: "Tarkkuus",
    upscalingText: "Terävöitetään tontun taikaa...",
    upscaleSuccess: "Taika on nyt entistä kirkkaampi!",
    btnCreateCert: "Luo Virallinen Tonttudiplomi",
    btnEditName: "Muokkaa tietoja",
    btnDownloadImage: "Tallenna Kuva",
    inputNamePlaceholder: "Tontun virallinen nimi",
    inputGroupNamePlaceholder: "Perheen tai ryhmän nimi",
    certTitle: "TONTTUDIPLOMI",
    certProof: "Täten juhlallisesti todistetaan, että",
    certOfficial: "on nimitetty Lapin viralliseksi tontuksi",
    certExperience: "Hän on osoittanut poikkeuksellista joulumieltä, suurta sydäntä ja läpäissyt taianomaisen Tonttu Kuvaus -muodonmuutoksen revontulien loisteessa Korvatunturin ikiaikaisten säädösten mukaisesti.",
    certPlaceDate: "Napapiiri, Rovaniemi",
    certMagicCert: "✨ Korvatunturin Hyväksymä ✨",
    btnPrint: "Lataa tai Tulosta",
    keyGateTitle: "Taikakoodi Tarvitaan",
    keyGateDesc: "Korkealaatuinen AI-taikuus vaatii oman API-avaimen (valitse maksullinen Google Cloud -projekti).",
    keyGateButton: "Aktivoi Taika-avain",
    keyGateBillingLink: "Lue lisää tonttujen kuluista"
  },
  EN: {
    title: "Elf Portrait",
    subtitle: "Discover your inner elf with Lapland magic",
    buttonBegin: "Begin the Magical Journey",
    smileText: "Smile for the elf camera",
    footerText: "Arctic AI Laboratory • Rovaniemi, Lapland ✨",
    capturing: "Capturing your spirit...",
    processing: "Inside the Elf Workshop...",
    processingSub: "Lapland's elves are weaving northern lights and Christmas wonder into your portrait",
    resultTitle: "Your Elf Portrait",
    backHome: "New Magic",
    errorTitle: "A snowy obstacle blocks the magic.",
    errorAction: "Try Again",
    groupSelectTitle: "Who enters the magic?",
    groupSelectSingle: "Single Elf",
    groupSelectSingleDesc: "Personal transformation",
    groupSelectGroup: "Family & Friends",
    groupSelectGroupDesc: "A shared elven moment for everyone",
    selectStyleTitle: "Choose Your Elf Style",
    styleClassic: "Classic",
    styleFrost: "Frost Elf",
    styleForest: "Forest Elf",
    styleRoyal: "Royal Elf",
    btnStartMagic: "Cast Magic",
    btnUpscale: "Magical Upscale",
    upscaleLevelLabel: "Resolution",
    upscalingText: "Enhancing the elven magic...",
    upscaleSuccess: "The magic is clearer than ever!",
    btnCreateCert: "Create Official Elf Diploma",
    btnEditName: "Edit Information",
    btnDownloadImage: "Save Image",
    inputNamePlaceholder: "Official Elf Name",
    inputGroupNamePlaceholder: "Family or Group name",
    certTitle: "ELF DIPLOMA",
    certProof: "This is to solemnly certify that",
    certOfficial: "is officially appointed as a Lapland Elf",
    certExperience: "Having demonstrated exceptional Christmas spirit, a kind heart, and successfully undergone the magical Tonttu Kuvaus transformation under the brilliance of the aurora borealis, in accordance with the ancient laws of the North Pole.",
    certPlaceDate: "Arctic Circle, Rovaniemi",
    certMagicCert: "✨ North Pole Certified ✨",
    btnPrint: "Download or Print",
    keyGateTitle: "Magic Key Required",
    keyGateDesc: "High-quality AI magic requires your own API key (select a paid Google Cloud project).",
    keyGateButton: "Activate Magic Key",
    keyGateBillingLink: "Learn more about elf costs"
  }
};
